# Site settings
title: Jekyll Sandbox
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rennt.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Sitemap gem
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

permalink: /:categories/:title/

prose:
  ignore: ['.gitignore', '_config.yml', 'feed.xml', 'index.html', '_includes', '_layouts', '_sass', 'css']
  siteurl: 'http://rennt.github.io/'
  media: 'media'
  relativeLinks: 'http://rennt.github.io/links.jsonp'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "categories"
        field:
          element: "select"
          label: "Add Category"
          placeholder: "Choose Category"
          options:
            - name: "Article"
              value: "articles"
            - name: "Podcast"
              value: "podcast"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Training"
              value: "training"
            - name: "Nutrition"
              value: "nutrition"
            - name: "Meditation Shit"
              value: "hipster"
