# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rennt.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

prose:
  #ignore: ['.gitignore', '_config.yml', 'feed.xml', 'index.html', '_includes', '_layouts', '_sass', 'css']
  siteurl: 'http://rennt.github.io/'
  media: 'media'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      #- name: "title"
      #  field:
      #    element: "text"
      #    label: "title"
      - name: "category"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Training"
              value: "training"
            - name: "Nutrition"
              value: "nutrition"
            - name: "Meditation-Shit"
              value: "hipster"

